name: Api in docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN}}
      
      - name: Build Docker image
        run: docker build -t felixdvk/image_meteo:latest .
      
      - name: Push Docker image dans Docker Hub
        run: docker push felixdvk/image_meteo:latest
      
      - name: Run app
        run: |
          pip install flask
          python app.py