name: Meteo Workflow

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push Docker image dans Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: felixdvk/image_meteo:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
